name: plasess
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.1.1
  wave_widget: ^0.1.1
  local_auth: ^3.0.0
  fluttertoast: ^9.0.0
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true  # <-- هذا السطر مضاف لتوليد ملفات Localizations

  # assets and fonts remain unchanged
  assets:
    - assets/images/