// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRxSCjBEnngkuOABsCpJ6OIVoACyStZ8',
    appId: '1:857099557864:web:1d2879e633198bc310625d',
    messagingSenderId: '857099557864',
    projectId: 'donation-platform-e7e74',
    authDomain: 'donation-platform-e7e74.firebaseapp.com',
    storageBucket: 'donation-platform-e7e74.firebasestorage.app',
    measurementId: 'G-1FYP8KX6N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqRCYfaqM6UHUuoWlpW7OlZLxr8QdfBiw',
    appId: '1:857099557864:android:7f726abfb9afaf5710625d',
    messagingSenderId: '857099557864',
    projectId: 'donation-platform-e7e74',
    storageBucket: 'donation-platform-e7e74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7FJhRAHnCm_1EqEujUmmP4CJHzqixj8',
    appId: '1:857099557864:ios:696d2f1e3b6fa78110625d',
    messagingSenderId: '857099557864',
    projectId: 'donation-platform-e7e74',
    storageBucket: 'donation-platform-e7e74.firebasestorage.app',
    iosBundleId: 'com.example.plasess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-7FJhRAHnCm_1EqEujUmmP4CJHzqixj8',
    appId: '1:857099557864:ios:696d2f1e3b6fa78110625d',
    messagingSenderId: '857099557864',
    projectId: 'donation-platform-e7e74',
    storageBucket: 'donation-platform-e7e74.firebasestorage.app',
    iosBundleId: 'com.example.plasess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnRxSCjBEnngkuOABsCpJ6OIVoACyStZ8',
    appId: '1:857099557864:web:e1d140f022757fa110625d',
    messagingSenderId: '857099557864',
    projectId: 'donation-platform-e7e74',
    authDomain: 'donation-platform-e7e74.firebaseapp.com',
    storageBucket: 'donation-platform-e7e74.firebasestorage.app',
    measurementId: 'G-T1GSGXZZXF',
  );
}
